# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "accounts", :force => true do |t|
    t.column "number", :string, :limit => 30, :null => false
    t.column "type", :string, :limit => 50, :null => false
    t.column "employee_id", :integer
  end

  create_table "employees", :force => true do |t|
    t.column "first_name", :string, :limit => 30, :null => false
    t.column "last_name", :string, :limit => 30, :null => false
    t.column "occupation", :string, :limit => 50
    t.column "is_active", :boolean, :default => true, :null => false
  end

  create_table "inventory_items", :force => true do |t|
    t.column :name, :string, :limit => 200, :null => false
    t.column :code, :string, :limit => 10, :null => false
    t.column :measurement_unit, :string, :limit => 30, :null => false
    t.column :unit_price, :decimal, :precision => 8, :scale => 2, :null => false
  end

  create_table "inventory_transactions", :force => true do |t|
    t.column :transaction_date, :date, :null => false
    t.column :type, :string, :limit => 50, :null => false
  end

  create_table "transaction_entries", :force => true do |t|
    t.column :type, :string, :limit => 50, :null => false
    t.column :inventory_amount, :decimal, :precision => 8, :scale => 2, :null => false

    t.references :inventory_transaction
    t.references :inventory_item
    t.references :account
    t.references :employee
  end

end
